# Generated by Django 5.0.8 on 2024-08-13 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Femurkomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Femurkomponenten',
            },
        ),
        migrations.CreateModel(
            name='Inlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Inlays',
            },
        ),
        migrations.CreateModel(
            name='Kopf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Köpfe',
            },
        ),
        migrations.CreateModel(
            name='Lagerort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schrank', models.IntegerField(verbose_name='Schrank')),
                ('kiste', models.IntegerField(verbose_name='Kiste')),
            ],
            options={
                'verbose_name_plural': 'Lagerorte',
            },
        ),
        migrations.CreateModel(
            name='Patellaersatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Patellaersätze',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geburtsdatum', models.DateField(verbose_name='Geburtsdatum')),
                ('gewicht', models.FloatField(verbose_name='Gewicht')),
            ],
            options={
                'verbose_name_plural': 'Patienten',
            },
        ),
        migrations.CreateModel(
            name='Pfanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Pfannen',
            },
        ),
        migrations.CreateModel(
            name='Reoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reoperation', models.BooleanField(verbose_name='Reoperation')),
                ('reoperation_datum', models.DateField(verbose_name='Reoperationsdatum')),
            ],
            options={
                'verbose_name_plural': 'Reoperationen',
            },
        ),
        migrations.CreateModel(
            name='Schaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Schafte',
            },
        ),
        migrations.CreateModel(
            name='Tibiaplateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Tibiaplateaus',
            },
        ),
        migrations.CreateModel(
            name='Explantat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ursache', models.TextField(verbose_name='Ursache')),
                ('verfuegbarkeit', models.BooleanField(verbose_name='Verfügbarkeit')),
                ('herkunftsort', models.CharField(max_length=100, verbose_name='Herkunftsort')),
                ('entnahme_datum', models.DateField(blank=True, null=True, verbose_name='Entnahmedatum')),
                ('eingang_datum', models.DateField(verbose_name='Eingangsdatum')),
                ('bruchgeschehen', models.TextField(verbose_name='Bruchgeschehen')),
                ('nutzungsdauer', models.IntegerField(blank=True, null=True, verbose_name='Nutzungsdauer')),
                ('reinigung', models.BooleanField(verbose_name='Reinigung')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Bild')),
                ('owner', models.IntegerField(default=1, verbose_name='Besitzer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('femurkomponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.femurkomponente', verbose_name='Femurkomponente')),
                ('inlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.inlay', verbose_name='Inlay')),
                ('kopf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.kopf', verbose_name='Kopf')),
                ('lagerort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lagerort', verbose_name='Lagerort')),
                ('patellaersatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.patellaersatz', verbose_name='Patellaersatz')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.patient', verbose_name='Patient')),
                ('pfanne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.pfanne', verbose_name='Pfanne')),
                ('reoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.reoperation', verbose_name='Reoperation')),
                ('schaft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.schaft', verbose_name='Schaft')),
                ('tibiaplateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.tibiaplateau', verbose_name='Tibiaplateau')),
            ],
            options={
                'verbose_name_plural': 'Explantate',
            },
        ),
        migrations.CreateModel(
            name='FemurkomponenteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('femurkomponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.femurkomponente')),
            ],
            options={
                'verbose_name_plural': 'Femurkomponenten Details',
            },
        ),
        migrations.CreateModel(
            name='InlayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('inlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.inlay')),
            ],
            options={
                'verbose_name_plural': 'Inlays Details',
            },
        ),
        migrations.CreateModel(
            name='KopfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('kopf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kopf')),
            ],
            options={
                'verbose_name_plural': 'Köpfe Details',
            },
        ),
        migrations.CreateModel(
            name='PatellaersatzDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False, verbose_name='recycelt')),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('patellaersatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.patellaersatz')),
            ],
            options={
                'verbose_name_plural': 'Patellaersätze Details',
            },
        ),
        migrations.CreateModel(
            name='PfanneDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('pfanne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pfanne')),
            ],
            options={
                'verbose_name_plural': 'Pfannen Details',
            },
        ),
        migrations.CreateModel(
            name='SchaftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('schaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.schaft')),
            ],
            options={
                'verbose_name_plural': 'Schafte Details',
            },
        ),
        migrations.CreateModel(
            name='TibiaplateauDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('tibiaplateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tibiaplateau')),
            ],
            options={
                'verbose_name_plural': 'Tibiaplateaus Details',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonnummer')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bundesland')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postleitzahl')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stadt')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Profilbild')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
