# Generated by Django 5.0.1 on 2024-03-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Femurkomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Femurkomponenten',
            },
        ),
        migrations.CreateModel(
            name='Inlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
        ),
        migrations.CreateModel(
            name='Kopf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Köpfe',
            },
        ),
        migrations.CreateModel(
            name='Lagerort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schrank', models.IntegerField(verbose_name='Schrank')),
                ('kiste', models.IntegerField(verbose_name='Kiste')),
            ],
            options={
                'verbose_name_plural': 'Lagerorte',
            },
        ),
        migrations.CreateModel(
            name='Patellaersatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Patellaersätze',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geburtsdatum', models.DateField(verbose_name='Geburtsdatum')),
                ('gewicht', models.FloatField(verbose_name='Gewicht')),
            ],
            options={
                'verbose_name_plural': 'Patienten',
            },
        ),
        migrations.CreateModel(
            name='Pfanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Pfannen',
            },
        ),
        migrations.CreateModel(
            name='Reoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reoperation', models.BooleanField(verbose_name='Reoperation')),
                ('reoperation_datum', models.DateField(verbose_name='Reoperationsdatum')),
            ],
            options={
                'verbose_name_plural': 'Reperationen',
            },
        ),
        migrations.CreateModel(
            name='Schaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
            options={
                'verbose_name_plural': 'Schafte',
            },
        ),
        migrations.CreateModel(
            name='Tibiaplateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(verbose_name='Hersteller')),
                ('modell', models.CharField(verbose_name='Modell')),
                ('material', models.CharField(verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
            ],
        ),
        migrations.CreateModel(
            name='Explantat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ursache', models.TextField(verbose_name='Ursache')),
                ('verfuegbarkeit', models.BooleanField(verbose_name='Verfügbarkeit')),
                ('herkunftsort', models.CharField(verbose_name='Herkunftsort')),
                ('entnahme_datum', models.DateField(blank=True, null=True, verbose_name='Entnahmedatum')),
                ('eingang_datum', models.DateField(verbose_name='Eingangsdatum')),
                ('bruchgeschehen', models.TextField(verbose_name='Bruchgeschehen')),
                ('nutzungsdauer', models.IntegerField(blank=True, null=True, verbose_name='Nutzungsdauer')),
                ('reinigung', models.BooleanField(verbose_name='Reinigung')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Bild')),
                ('owner', models.IntegerField(default=1, verbose_name='Owner')),
                ('femurkomponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.femurkomponente')),
                ('inlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.inlay')),
                ('kopf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.kopf')),
                ('lagerort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lagerort')),
                ('patellaersatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.patellaersatz')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.patient')),
                ('pfanne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.pfanne')),
                ('reoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.reoperation')),
                ('schaft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.schaft')),
                ('tibiaplateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.tibiaplateau')),
            ],
            options={
                'verbose_name_plural': 'Explantate',
            },
        ),
    ]
