# Generated by Django 4.2.1 on 2023-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explantat',
            name='reoperation',
            field=models.ManyToManyField(blank=True, to='data.reoperation'),
        ),
    ]
