# Generated by Django 5.0.8 on 2024-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aktivitaet',
            field=models.TextField(blank=True, null=True, verbose_name='Aktivität'),
        ),
        migrations.AddField(
            model_name='patient',
            name='begleiterkrankungen',
            field=models.TextField(blank=True, null=True, verbose_name='Begleiterkrankungen'),
        ),
        migrations.AddField(
            model_name='patient',
            name='geschlecht',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groesse',
            field=models.FloatField(blank=True, null=True, verbose_name='Größe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_vorgeschichte',
            field=models.TextField(blank=True, null=True, verbose_name='Medizinische Vorgeschichte'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nachuntersuchungen',
            field=models.TextField(blank=True, null=True, verbose_name='Nachuntersuchungen'),
        ),
        migrations.AddField(
            model_name='patient',
            name='roentgenbilder',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Röntgenbilder'),
        ),
    ]
