# Generated by Django 4.2.1 on 2023-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_explantat_reoperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explantat',
            options={'verbose_name_plural': 'Explantate'},
        ),
        migrations.AlterModelOptions(
            name='femurkomponente',
            options={'verbose_name_plural': 'Femurkomponenten'},
        ),
        migrations.AlterModelOptions(
            name='kopf',
            options={'verbose_name_plural': 'Köpfe'},
        ),
        migrations.AlterModelOptions(
            name='lagerort',
            options={'verbose_name_plural': 'Lagerorte'},
        ),
        migrations.AlterModelOptions(
            name='patellaersatz',
            options={'verbose_name_plural': 'Patellaersätze'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patienten'},
        ),
        migrations.AlterModelOptions(
            name='pfanne',
            options={'verbose_name_plural': 'Pfannen'},
        ),
        migrations.AlterModelOptions(
            name='reoperation',
            options={'verbose_name_plural': 'Reperationen'},
        ),
        migrations.AlterModelOptions(
            name='schaft',
            options={'verbose_name_plural': 'Schafte'},
        ),
        migrations.AlterField(
            model_name='explantat',
            name='eingang_datum',
            field=models.DateField(verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='entnahme_datum',
            field=models.DateField(verbose_name='Entnahmedatum'),
        ),
        migrations.AlterField(
            model_name='reoperation',
            name='reoperation_datum',
            field=models.DateField(verbose_name='Reoperationsdatum'),
        ),
    ]
