# Generated by Django 5.0.8 on 2024-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_patient_aktivitaet_patient_begleiterkrankungen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='groesse',
        ),
        migrations.AddField(
            model_name='patient',
            name='groeße',
            field=models.FloatField(null=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='geschlecht',
            field=models.CharField(max_length=20, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='med_vorgeschichte',
            field=models.TextField(blank=True, null=True, verbose_name='Med. Vorgeschichte'),
        ),
    ]
