# Generated by Django 4.2.1 on 2023-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_explantat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explantat',
            name='bruchgeschehen',
            field=models.TextField(blank=True, verbose_name='Bruchgeschehen'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='eingang_datum',
            field=models.DateField(blank=True, verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='entnahme_datum',
            field=models.DateField(blank=True, verbose_name='Entnahmedatum'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='herkunftsort',
            field=models.CharField(blank=True, verbose_name='Herkunftsort'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='nutzungsdauer',
            field=models.IntegerField(blank=True, verbose_name='Nutzungsdauer'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='reinigung',
            field=models.BooleanField(blank=True, verbose_name='Reinigung'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='ursache',
            field=models.TextField(blank=True, verbose_name='Ursache'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='verfuegbarkeit',
            field=models.BooleanField(blank=True, verbose_name='Verfügbarkeit'),
        ),
    ]
