# Generated by Django 4.2.1 on 2023-10-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_explantat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explantat',
            name='reoperation',
        ),
        migrations.AddField(
            model_name='explantat',
            name='reoperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.reoperation'),
        ),
    ]
