# Generated by Django 5.0.8 on 2024-08-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_patient_groesse_patient_groeße_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(max_length=100, verbose_name='Modell')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('groeße', models.FloatField(verbose_name='Größe')),
                ('legierung', models.CharField(max_length=100, verbose_name='Legierung')),
            ],
            options={
                'verbose_name_plural': 'Stents',
            },
        ),
        migrations.AddField(
            model_name='explantat',
            name='stent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.stent', verbose_name='Stent'),
        ),
        migrations.CreateModel(
            name='StentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False, verbose_name='recycelt')),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('stent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.stent')),
            ],
            options={
                'verbose_name_plural': 'Stents Details',
            },
        ),
    ]
