# Generated by Django 4.2.1 on 2023-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_explantat_bruchgeschehen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femurkomponente',
            name='groeße',
            field=models.FloatField(null=True, verbose_name='Größe'),
        ),
    ]
