# Generated by Django 5.0.8 on 2024-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_stent_explantat_stent_stentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='femurkomponente',
            name='fixation_type',
            field=models.CharField(blank=True, choices=[('zementiert', 'Zementiert'), ('unzementiert', 'Unzementiert'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Fixationsmethode'),
        ),
        migrations.AddField(
            model_name='femurkomponente',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='femurkomponente',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='femurkomponente',
            name='surface_coating',
            field=models.CharField(blank=True, choices=[('Titan', 'Titan'), ('Hydroxylapatit', 'Hydroxylapatit'), ('keine', 'Keine')], max_length=100, verbose_name='Oberflächenbeschichtung'),
        ),
        migrations.AddField(
            model_name='inlay',
            name='gliding_pairing',
            field=models.CharField(blank=True, choices=[('metall_auf_metall', 'Metall auf Metall'), ('metall_auf_polyethylen', 'Metall auf Polyethylen'), ('keramik_auf_keramik', 'Keramik auf Keramik')], max_length=100, verbose_name='Gleitpaarung'),
        ),
        migrations.AddField(
            model_name='inlay',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='inlay',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='kopf',
            name='gliding_pairing',
            field=models.CharField(blank=True, choices=[('metall_auf_metall', 'Metall auf Metall'), ('metall_auf_polyethylen', 'Metall auf Polyethylen'), ('keramik_auf_keramik', 'Keramik auf Keramik')], max_length=100, verbose_name='Gleitpaarung'),
        ),
        migrations.AddField(
            model_name='kopf',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='kopf',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='patellaersatz',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='patellaersatz',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='fixation_type',
            field=models.CharField(blank=True, choices=[('zementiert', 'Zementiert'), ('unzementiert', 'Unzementiert'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Fixationsmethode'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='gliding_pairing',
            field=models.CharField(blank=True, choices=[('metall_auf_metall', 'Metall auf Metall'), ('metall_auf_polyethylen', 'Metall auf Polyethylen'), ('keramik_auf_keramik', 'Keramik auf Keramik')], max_length=100, verbose_name='Gleitpaarung'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='surface_coating',
            field=models.CharField(blank=True, choices=[('Titan', 'Titan'), ('Hydroxylapatit', 'Hydroxylapatit'), ('keine', 'Keine')], max_length=100, verbose_name='Oberflächenbeschichtung'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='design',
            field=models.CharField(blank=True, choices=[('gerader_schaft', 'Gerader Schaft'), ('anatomisch', 'Anatomischer Schaft'), ('kurzschaft', 'Kurzschaft'), ('modular', 'Modularer Schaft')], max_length=50, verbose_name='Design'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='fixation_type',
            field=models.CharField(blank=True, choices=[('zementiert', 'Zementiert'), ('unzementiert', 'Unzementiert'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Fixationsmethode'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='surface_coating',
            field=models.CharField(blank=True, choices=[('Titan', 'Titan'), ('Hydroxylapatit', 'Hydroxylapatit'), ('keine', 'Keine')], max_length=100, verbose_name='Oberflächenbeschichtung'),
        ),
        migrations.AddField(
            model_name='stent',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='stent',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='tibiaplateau',
            name='fixation_type',
            field=models.CharField(blank=True, choices=[('zementiert', 'Zementiert'), ('unzementiert', 'Unzementiert'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Fixationsmethode'),
        ),
        migrations.AddField(
            model_name='tibiaplateau',
            name='mrt_compatibility',
            field=models.BooleanField(default=False, verbose_name='MRT-Kompatibilität'),
        ),
        migrations.AddField(
            model_name='tibiaplateau',
            name='revision_friendly',
            field=models.BooleanField(default=False, verbose_name='Revisionstauglichkeit'),
        ),
        migrations.AddField(
            model_name='tibiaplateau',
            name='surface_coating',
            field=models.CharField(blank=True, choices=[('Titan', 'Titan'), ('Hydroxylapatit', 'Hydroxylapatit'), ('keine', 'Keine')], max_length=100, verbose_name='Oberflächenbeschichtung'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='stent',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='groeße',
            field=models.FloatField(verbose_name='Größe in mm'),
        ),
    ]
