# Generated by Django 5.0.6 on 2024-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_explantat_created_at_explantat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='femurkomponente',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='inlay',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='kopf',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='patellaersatz',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='pfanne',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='schaft',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
        migrations.AddField(
            model_name='tibiaplateau',
            name='recycelt',
            field=models.BooleanField(blank=True, null=True, verbose_name='recycelt'),
        ),
    ]
