# Generated by Django 5.0.8 on 2024-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_femurkomponente_fixation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagerort',
            name='einrichtung',
            field=models.CharField(blank=True, max_length=50, verbose_name='Einrichtung'),
        ),
    ]
