# Generated by Django 5.0.6 on 2024-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlay',
            options={'verbose_name_plural': 'Inlays'},
        ),
        migrations.AlterModelOptions(
            name='tibiaplateau',
            options={'verbose_name_plural': 'Tibiaplateaus'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Benutzerprofile'},
        ),
        migrations.AlterField(
            model_name='explantat',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Besitzer'),
        ),
    ]
