# Generated by Django 5.0.8 on 2024-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_lagerort_einrichtung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagerort',
            name='einrichtung',
            field=models.CharField(max_length=50, verbose_name='Einrichtung'),
        ),
    ]
