# Generated by Django 4.2.1 on 2023-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_explantat_femurkomponente_alter_explantat_kopf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femurkomponente',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='lagerort',
            name='kiste',
            field=models.IntegerField(blank=True, verbose_name='Kiste'),
        ),
        migrations.AlterField(
            model_name='lagerort',
            name='schrank',
            field=models.IntegerField(blank=True, verbose_name='Schrank'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='geburtsdatum',
            field=models.DateField(blank=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gewicht',
            field=models.FloatField(blank=True, verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='reoperation',
            name='reoperation',
            field=models.BooleanField(blank=True, verbose_name='Reoperation'),
        ),
        migrations.AlterField(
            model_name='reoperation',
            name='reoperation_datum',
            field=models.DateField(blank=True, verbose_name='Reoperationsdatum'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='groeße',
            field=models.FloatField(blank=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='hersteller',
            field=models.CharField(blank=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='material',
            field=models.CharField(blank=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='modell',
            field=models.CharField(blank=True, verbose_name='Modell'),
        ),
    ]
