# Generated by Django 5.0.6 on 2024-05-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_inlay_options_alter_tibiaplateau_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reoperation',
            options={'verbose_name_plural': 'Reoperationen'},
        ),
    ]
