# Generated by Django 5.0.8 on 2024-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_lagerort_einrichtung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='geschlecht',
            field=models.CharField(choices=[('maennlich', 'Männlich'), ('weiblich', 'Weiblich'), ('divers', 'Divers')], max_length=20, null=True, verbose_name='Geschlecht'),
        ),
    ]
