# Generated by Django 5.0.6 on 2024-05-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_reoperation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explantat',
            name='femurkomponente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.femurkomponente', verbose_name='Femurkomponente'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='inlay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.inlay', verbose_name='Inlay'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='kopf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.kopf', verbose_name='Kopf'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='lagerort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lagerort', verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='patellaersatz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.patellaersatz', verbose_name='Patellaersatz'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='pfanne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.pfanne', verbose_name='Pfanne'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='reoperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.reoperation', verbose_name='Reoperation'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='schaft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.schaft', verbose_name='Schaft'),
        ),
        migrations.AlterField(
            model_name='explantat',
            name='tibiaplateau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.tibiaplateau', verbose_name='Tibiaplateau'),
        ),
    ]
