# Generated by Django 4.2.7 on 2023-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_explantat_entnahme_datum_alter_explantat_inlay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explantat',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Bild'),
        ),
    ]
