# Generated by Django 5.0.6 on 2024-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_explantat_femurkomponente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femurkomponente',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='femurkomponente',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='inlay',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='kopf',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='patellaersatz',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='pfanne',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='schaft',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='hersteller',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='modell',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='tibiaplateau',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
    ]
