# Generated by Django 5.0.6 on 2024-05-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_femurkomponente_hersteller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemurkomponenteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('femurkomponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.femurkomponente')),
            ],
        ),
        migrations.CreateModel(
            name='InlayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('inlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.inlay')),
            ],
        ),
        migrations.CreateModel(
            name='KopfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('kopf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kopf')),
            ],
        ),
        migrations.CreateModel(
            name='PatellaersatzDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('patellaersatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.patellaersatz')),
            ],
        ),
        migrations.CreateModel(
            name='PfanneDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('pfanne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pfanne')),
            ],
        ),
        migrations.CreateModel(
            name='SchaftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('schaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.schaft')),
            ],
        ),
        migrations.CreateModel(
            name='TibiaplateauDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycelt', models.BooleanField(default=False)),
                ('explantat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.explantat')),
                ('tibiaplateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tibiaplateau')),
            ],
        ),
    ]
