# Generated by Django 5.0.6 on 2024-05-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_femurkomponentedetails_inlaydetails_kopfdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='femurkomponentedetails',
            options={'verbose_name_plural': 'Femurkomponenten Details'},
        ),
        migrations.AlterModelOptions(
            name='inlaydetails',
            options={'verbose_name_plural': 'Inlays Details'},
        ),
        migrations.AlterModelOptions(
            name='kopfdetails',
            options={'verbose_name_plural': 'Köpfe Details'},
        ),
        migrations.AlterModelOptions(
            name='patellaersatzdetails',
            options={'verbose_name_plural': 'Patellaersätze Details'},
        ),
        migrations.AlterModelOptions(
            name='pfannedetails',
            options={'verbose_name_plural': 'Pfannen Details'},
        ),
        migrations.AlterModelOptions(
            name='schaftdetails',
            options={'verbose_name_plural': 'Schafte Details'},
        ),
        migrations.AlterModelOptions(
            name='tibiaplateaudetails',
            options={'verbose_name_plural': 'Tibiaplateaus Details'},
        ),
    ]
