# Generated by Django 5.0.6 on 2024-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_femurkomponentedetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patellaersatzdetails',
            name='recycelt',
            field=models.BooleanField(default=False, verbose_name='recycelt'),
        ),
    ]
