# Generated by Django 5.0.6 on 2024-05-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_patellaersatzdetails_recycelt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femurkomponente',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='inlay',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='kopf',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='patellaersatz',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='pfanne',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='schaft',
            name='recycelt',
        ),
        migrations.RemoveField(
            model_name='tibiaplateau',
            name='recycelt',
        ),
    ]
